config/routes.rb
Loja::Application.routes.draw do
  get "clientes/login"

  get "clientes/process_login"

  get "clientes/logout"

  get "clientes/my_account"

  get "clienter/login"

  get "clienter/process_login"

  get "clienter/logount"

  get "clienter/my_account"

  get "user/login"

  get "user/process_login"

  get "user/logount"

  get "user/my_account"

  get "login/login"

  resources :tipos

  resources :produtos

  resources :pedidos

  resources :clientes

  get "home/index"

   root :to => 'home#index'
   match 'produtos/:id/busca' => 'produtos#busca' , :as => :busca_produtos, :via => :get
   match 'clientes/process_login' => 'clientes#process_login', :via => [:get, :post]
   match 'clientes/login' => 'clientes#login', :as => :clientes_login, :via => [:get, :post]
   match 'clientes/logout' => 'clientes#logout', :as => :clientes_logout, :via => [:get, :post]

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :cidade, :email, :endereco, :id, :nome, :numero, :senha, :uf
  validates :cidade, :email, :endereco, :nome, :numero, :senha, :uf, :presence => true
  validates :email, :uniqueness => true
  validates :numero, :numericality => { :only_integer => true}
  
  def self.authenticate(email, senha)
       find_by_email_and_senha(email,senha)
    end
  
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cadastro realizado com sucesso' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
  

    def login
      @cliente = Cliente.new
      @cliente.email = params[:username]
    end

    def process_login
      if cliente = Cliente.authenticate(params[:user][:username],params[:user][:password])
        session[:id] = cliente.id # Remember the user's id during this session
        redirect_to session[:return_to] || '/'
      else
        flash[:error] = 'Usuario ou senha invalidos.'
        redirect_to :action => 'login' #, :username => params[:user][:username]
      end
    end

    def logout
      reset_session
      flash[:message] = 'Sessao encerrada.'
      redirect_to :action => 'login'
    end

    def my_account
    end


  
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.password_field :senha %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :uf %><br />
    <%= f.text_field :uf %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :numero %><br />
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Email</th>
    <th>Senha</th>
    <th>Cidade</th>
    <th>Uf</th>
    <th>Endereco</th>
    <th>Numero</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.id %></td>
    <td><%= cliente.nome %></td>
    <td><%= cliente.email %></td>
    <td><%= cliente.senha %></td>
    <td><%= cliente.cidade %></td>
    <td><%= cliente.uf %></td>
    <td><%= cliente.endereco %></td>
    <td><%= cliente.numero %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/login.html.erb
  <h1>Login</h1>
  <%= form_tag :action => 'process_login' 
  %>
  Username: <%= text_field "user", "username" %><br>&#x00A;
    Password: <%= password_field "user", "password" %><br>&#x00A;
<br>
    <%= submit_tag 'Login' %>

<% if flash[:message] %><div><%= flash[:message] %></div><% end %>
  <% if flash[:error] %><div><%= flash[:error] %></div><% end %>

app/views/clientes/logout.html.erb
<h1>Clientes#logount</h1>
<p>Find me in app/views/clientes/logount.html.erb</p>

app/views/clientes/my_account.html.erb
<!-- app/views/user/my_account.rhtml -->
  <h1>Account Info</h1>

  <p>Your username is <%= Cliente.find(session[:id]).email %>

app/views/clientes/new.html.erb
<h1>Cadastre-se</h1>

<%= render 'form' %>

app/views/clientes/process_login.html.erb
<h1>Clientes#process_login</h1>
<p>Find me in app/views/clientes/process_login.html.erb</p>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @cliente.id %>
</p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @cliente.email %>
</p>

<p>
  <b>Senha:</b>
  <%= @cliente.senha %>
</p>

<p>
  <b>Cidade:</b>
  <%= @cliente.cidade %>
</p>

<p>
  <b>Uf:</b>
  <%= @cliente.uf %>
</p>

<p>
  <b>Endereco:</b>
  <%= @cliente.endereco %>
</p>

<p>
  <b>Numero:</b>
  <%= @cliente.numero %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>