config/routes.rb
Loja::Application.routes.draw do
  get "clientes/login"

  get "clientes/process_login"

  get "clientes/logout"

  get "clientes/my_account"

  get "clienter/login"

  get "clienter/process_login"

  get "clienter/logount"

  get "clienter/my_account"

  get "user/login"

  get "user/process_login"

  get "user/logount"

  get "user/my_account"

  get "login/login"

  resources :tipos

  resources :produtos

  resources :pedidos

  resources :clientes

  get "home/index"

   root :to => 'home#index'
   match 'produtos/:id/busca' => 'produtos#busca' , :as => :busca_produtos, :via => :get
   match 'clientes/process_login' => 'clientes#process_login', :via => [:get, :post]
   match 'clientes/login' => 'clientes#login', :as => :clientes_login, :via => [:get, :post]
   match 'clientes/logout' => 'clientes#logout', :as => :clientes_logout, :via => [:get, :post]

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  attr_accessible :id, :id_cliente, :status
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedidos }
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/new
  # GET /pedidos/new.json
  def new
    @pedido = Pedido.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/1/edit
  def edit
    @pedido = Pedido.find(params[:id])
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(params[:pedido])

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render json: @pedido, status: :created, location: @pedido }
      else
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pedidos/1
  # PUT /pedidos/1.json
  def update
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      if @pedido.update_attributes(params[:pedido])
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :id_cliente %><br />
    <%= f.number_field :id_cliente %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listing pedidos</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Id cliente</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pedidos.each do |pedido| %>
  <tr>
    <td><%= pedido.id %></td>
    <td><%= pedido.id_cliente %></td>
    <td><%= pedido.status %></td>
    <td><%= link_to 'Show', pedido %></td>
    <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
    <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render 'form' %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @pedido.id %>
</p>

<p>
  <b>Id cliente:</b>
  <%= @pedido.id_cliente %>
</p>

<p>
  <b>Status:</b>
  <%= @pedido.status %>
</p>


<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>