config/routes.rb
Loja::Application.routes.draw do
  get "clientes/login"

  get "clientes/process_login"

  get "clientes/logout"

  get "clientes/my_account"

  get "clienter/login"

  get "clienter/process_login"

  get "clienter/logount"

  get "clienter/my_account"

  get "user/login"

  get "user/process_login"

  get "user/logount"

  get "user/my_account"

  get "login/login"

  resources :tipos

  resources :produtos

  resources :pedidos

  resources :clientes

  get "home/index"

   root :to => 'home#index'
   match 'produtos/:id/busca' => 'produtos#busca' , :as => :busca_produtos, :via => :get
   match 'clientes/process_login' => 'clientes#process_login', :via => [:get, :post]
   match 'clientes/login' => 'clientes#login', :as => :clientes_login, :via => [:get, :post]
   match 'clientes/logout' => 'clientes#logout', :as => :clientes_logout, :via => [:get, :post]

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :descricao, :id, :nome, :tipo, :valor
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  def busca
    @produtos = Produto.where('tipo = ?', params[:id])
    respond_to do |format|
      format.html # busca.html.erb
      format.json { render json: @produtos }
    end
  end


  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.number_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :valor %><br />
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/busca.html.erb
<h1>Lista de Produtos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Valor</th>
    <th></th>
  </tr>

<% @produtos.each do |prod| %>
  <tr>
    <td><%= prod.nome %></td>
    <td><%= prod.valor %></td>
    <td><%= link_to 'Detalhes', prod %></td>
  </tr>
<% end %>
</table>

<br />

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render 'form' %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<h1>Listing produtos</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Tipo</th>
    <th>Descricao</th>
    <th>Valor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @produtos.each do |produto| %>
  <tr>
    <td><%= produto.id %></td>
    <td><%= produto.nome %></td>
    <td><%= produto.tipo %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.valor %></td>
    <td><%= link_to 'Show', produto %></td>
    <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
    <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render 'form' %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalhes do produto</h1>
<p>
  <b>Nome:</b>
  <%= @produto.nome %>
</p>

<p>
  <b>Tipo:</b>
  <%= @produto.tipo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @produto.descricao %>
</p>

<p>
  <b>Valor:</b>
  <%= @produto.valor %>
</p>

<%= link_to 'Comprar', '' %>