config/routes.rb
Loja::Application.routes.draw do
  get "clientes/login"

  get "clientes/process_login"

  get "clientes/logout"

  get "clientes/my_account"

  get "clienter/login"

  get "clienter/process_login"

  get "clienter/logount"

  get "clienter/my_account"

  get "user/login"

  get "user/process_login"

  get "user/logount"

  get "user/my_account"

  get "login/login"

  resources :tipos

  resources :produtos

  resources :pedidos

  resources :clientes

  get "home/index"

   root :to => 'home#index'
   match 'produtos/:id/busca' => 'produtos#busca' , :as => :busca_produtos, :via => :get
   match 'clientes/process_login' => 'clientes#process_login', :via => [:get, :post]
   match 'clientes/login' => 'clientes#login', :as => :clientes_login, :via => [:get, :post]
   match 'clientes/logout' => 'clientes#logout', :as => :clientes_logout, :via => [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
   <head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


       <title>Loja Virtual</title>
   </head>
   <body>
      <div id="main">
         <div id="header">
            <img src="/assets/logo_loja.png" />
         </div>
         <div id="sidebar">
            <ul id="menubv">
            	<% if !session[:id] %>
            	<li><%= link_to 'Cadastre-se', new_cliente_path %></li>
	            <li><%= link_to 'Entrar', clientes_login_path %></li>
            	<% else %>
            	<li><%= link_to 'Sair', clientes_logout_path %></li>
            	<% end %>
            	<% 
            	@tipos = Tipo.all
            	@tipos.each do |tipo| %>
					<li><%= link_to tipo.nome, busca_produtos_path(:id => tipo.id) %></li>
				<% end %>

            </ul>
             <br>&nbsp;
             <% if session[:id] %>
             	Usuário: &nbsp;
             	<%= Cliente.find(session[:id]).email %><br>
             <% end %><br>&nbsp;
         </div>
          
         <div id="content">
			<%= yield %>
         </div>
         <div id="footer"><center>
             <br>&nbsp;
             Loja Virtual
             <br>&nbsp;
                 </center>
        </div>
          
      </div>
   </body>
</html>